// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: proto/chunker/chunker.proto

package chunker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChunkRequest contains the information needed to chunk a file.
type ChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRequest) Reset() {
	*x = ChunkRequest{}
	mi := &file_proto_chunker_chunker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRequest) ProtoMessage() {}

func (x *ChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chunker_chunker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRequest.ProtoReflect.Descriptor instead.
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_chunker_chunker_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ChunkRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ChunkRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// ChunkResult represents a single semantic chunk extracted from a file.
type ChunkResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	StartLine     int32                  `protobuf:"varint,4,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine       int32                  `protobuf:"varint,5,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	Context       []string               `protobuf:"bytes,6,rep,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkResult) Reset() {
	*x = ChunkResult{}
	mi := &file_proto_chunker_chunker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkResult) ProtoMessage() {}

func (x *ChunkResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chunker_chunker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkResult.ProtoReflect.Descriptor instead.
func (*ChunkResult) Descriptor() ([]byte, []int) {
	return file_proto_chunker_chunker_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChunkResult) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ChunkResult) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ChunkResult) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *ChunkResult) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *ChunkResult) GetContext() []string {
	if x != nil {
		return x.Context
	}
	return nil
}

// ChunkResponse contains the chunks produced from a file.
type ChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*ChunkResult         `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkResponse) Reset() {
	*x = ChunkResponse{}
	mi := &file_proto_chunker_chunker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkResponse) ProtoMessage() {}

func (x *ChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chunker_chunker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkResponse.ProtoReflect.Descriptor instead.
func (*ChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_chunker_chunker_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkResponse) GetChunks() []*ChunkResult {
	if x != nil {
		return x.Chunks
	}
	return nil
}

var File_proto_chunker_chunker_proto protoreflect.FileDescriptor

const file_proto_chunker_chunker_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/chunker/chunker.proto\x12\achunker\"`\n" +
	"\fChunkRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"\xa7\x01\n" +
	"\vChunkResult\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"start_line\x18\x04 \x01(\x05R\tstartLine\x12\x19\n" +
	"\bend_line\x18\x05 \x01(\x05R\aendLine\x12\x18\n" +
	"\acontext\x18\x06 \x03(\tR\acontext\"=\n" +
	"\rChunkResponse\x12,\n" +
	"\x06chunks\x18\x01 \x03(\v2\x14.chunker.ChunkResultR\x06chunks2H\n" +
	"\x0eChunkerService\x126\n" +
	"\x05Chunk\x12\x15.chunker.ChunkRequest\x1a\x16.chunker.ChunkResponseB(Z&github.com/zoobzio/vicky/proto/chunkerb\x06proto3"

var (
	file_proto_chunker_chunker_proto_rawDescOnce sync.Once
	file_proto_chunker_chunker_proto_rawDescData []byte
)

func file_proto_chunker_chunker_proto_rawDescGZIP() []byte {
	file_proto_chunker_chunker_proto_rawDescOnce.Do(func() {
		file_proto_chunker_chunker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chunker_chunker_proto_rawDesc), len(file_proto_chunker_chunker_proto_rawDesc)))
	})
	return file_proto_chunker_chunker_proto_rawDescData
}

var file_proto_chunker_chunker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_chunker_chunker_proto_goTypes = []any{
	(*ChunkRequest)(nil),  // 0: chunker.ChunkRequest
	(*ChunkResult)(nil),   // 1: chunker.ChunkResult
	(*ChunkResponse)(nil), // 2: chunker.ChunkResponse
}
var file_proto_chunker_chunker_proto_depIdxs = []int32{
	1, // 0: chunker.ChunkResponse.chunks:type_name -> chunker.ChunkResult
	0, // 1: chunker.ChunkerService.Chunk:input_type -> chunker.ChunkRequest
	2, // 2: chunker.ChunkerService.Chunk:output_type -> chunker.ChunkResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_chunker_chunker_proto_init() }
func file_proto_chunker_chunker_proto_init() {
	if File_proto_chunker_chunker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chunker_chunker_proto_rawDesc), len(file_proto_chunker_chunker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chunker_chunker_proto_goTypes,
		DependencyIndexes: file_proto_chunker_chunker_proto_depIdxs,
		MessageInfos:      file_proto_chunker_chunker_proto_msgTypes,
	}.Build()
	File_proto_chunker_chunker_proto = out.File
	file_proto_chunker_chunker_proto_goTypes = nil
	file_proto_chunker_chunker_proto_depIdxs = nil
}
