coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      default:
        target: 80%

flags:
  unit:
    paths:
      - "*.go"
      - "!testing/**"
    carryforward: true
  integration:
    paths:
      - "testing/integration/**"
    carryforward: true
