// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: indexer.proto

package indexer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexRequest contains the information needed to run a SCIP indexer.
type IndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RepositoryId  int64                  `protobuf:"varint,2,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	VersionId     int64                  `protobuf:"varint,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Owner         string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	RepoName      string                 `protobuf:"bytes,6,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	Tag           string                 `protobuf:"bytes,7,opt,name=tag,proto3" json:"tag,omitempty"`
	CommitSha     string                 `protobuf:"bytes,8,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	Language      string                 `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_indexer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{0}
}

func (x *IndexRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *IndexRequest) GetRepositoryId() int64 {
	if x != nil {
		return x.RepositoryId
	}
	return 0
}

func (x *IndexRequest) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *IndexRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IndexRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *IndexRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *IndexRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *IndexRequest) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *IndexRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// IndexResult contains the output from a SCIP indexer.
type IndexResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	VersionId     int64                  `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	IndexData     []byte                 `protobuf:"bytes,3,opt,name=index_data,json=indexData,proto3" json:"index_data,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResult) Reset() {
	*x = IndexResult{}
	mi := &file_indexer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResult) ProtoMessage() {}

func (x *IndexResult) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResult.ProtoReflect.Descriptor instead.
func (*IndexResult) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{1}
}

func (x *IndexResult) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *IndexResult) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *IndexResult) GetIndexData() []byte {
	if x != nil {
		return x.IndexData
	}
	return nil
}

func (x *IndexResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_indexer_proto protoreflect.FileDescriptor

const file_indexer_proto_rawDesc = "" +
	"\n" +
	"\rindexer.proto\x12\aindexer\"\x82\x02\n" +
	"\fIndexRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12#\n" +
	"\rrepository_id\x18\x02 \x01(\x03R\frepositoryId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\x03R\tversionId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\x12\x1b\n" +
	"\trepo_name\x18\x06 \x01(\tR\brepoName\x12\x10\n" +
	"\x03tag\x18\a \x01(\tR\x03tag\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\b \x01(\tR\tcommitSha\x12\x1a\n" +
	"\blanguage\x18\t \x01(\tR\blanguage\"x\n" +
	"\vIndexResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\x03R\tversionId\x12\x1d\n" +
	"\n" +
	"index_data\x18\x03 \x01(\fR\tindexData\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2F\n" +
	"\x0eIndexerService\x124\n" +
	"\x05Index\x12\x15.indexer.IndexRequest\x1a\x14.indexer.IndexResultB(Z&github.com/zoobzio/vicky/proto/indexerb\x06proto3"

var (
	file_indexer_proto_rawDescOnce sync.Once
	file_indexer_proto_rawDescData []byte
)

func file_indexer_proto_rawDescGZIP() []byte {
	file_indexer_proto_rawDescOnce.Do(func() {
		file_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexer_proto_rawDesc), len(file_indexer_proto_rawDesc)))
	})
	return file_indexer_proto_rawDescData
}

var file_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_indexer_proto_goTypes = []any{
	(*IndexRequest)(nil), // 0: indexer.IndexRequest
	(*IndexResult)(nil),  // 1: indexer.IndexResult
}
var file_indexer_proto_depIdxs = []int32{
	0, // 0: indexer.IndexerService.Index:input_type -> indexer.IndexRequest
	1, // 1: indexer.IndexerService.Index:output_type -> indexer.IndexResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_indexer_proto_init() }
func file_indexer_proto_init() {
	if File_indexer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexer_proto_rawDesc), len(file_indexer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_indexer_proto_goTypes,
		DependencyIndexes: file_indexer_proto_depIdxs,
		MessageInfos:      file_indexer_proto_msgTypes,
	}.Build()
	File_indexer_proto = out.File
	file_indexer_proto_goTypes = nil
	file_indexer_proto_depIdxs = nil
}
